CREATE TABLE IF NOT EXISTS User (
  userID VARCHAR(255) PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  verified BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS Album (
  albumID CHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  thumbnailURL TEXT NOT NULL,
  user VARCHAR(255) NOT NULL,
  userID VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userID) REFERENCES User(userID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Photo (
  photoID CHAR(36) PRIMARY KEY,
  albumID CHAR(36) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  tags TEXT,
  photoURL TEXT NOT NULL,
  EXIF JSON,
  user VARCHAR(255) NOT NULL,
  userID VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (albumID) REFERENCES Album(albumID) ON DELETE CASCADE,
  FOREIGN KEY (userID) REFERENCES User(userID) ON DELETE CASCADE
);
